name: havka
description: Health & Lifestyle

publish_to: 'none'

version: 1.0.0+66

environment:
  sdk: ">=3.0.0"

dependencies:
  camera: ^0.10.3+2
  device_info_plus: ^9.0.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  cached_network_image: ^3.2.3
  share_plus: ^7.2.2
  health: ^12.0.1
  lottie: ^2.2.0
  shimmer: ^2.0.0
  http: ^1.2.1
  intl: ^0.19.0
  crypto: ^3.0.1
  dio: ^5.7.0
  sign_in_with_apple: ^6.1.0
  go_router: ^14.8.0
  google_fonts: ^6.1.0
  collection: ^1.18.0
  image_picker: ^1.1.2
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^6.1.0
  firebase_messaging: ^14.9.2
  google_mlkit_barcode_scanning: ^0.12.0
  google_mlkit_text_recognition: ^0.13.0
  flutter_reactive_ble: ^5.0.2
  firebase_auth: 4.16.0
  firebase_core: ^2.32.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.4.0
  pull_to_refresh: ^2.0.0
  cloud_firestore: 4.17.5
  json_serializable: ^6.6.1
  lint: ^1.5.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Antonio
      fonts:
          - asset: assets/fonts/Antonio-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
    - family: AveriaSansLibre
      fonts:
        - asset: assets/fonts/AveriaSansLibre-Regular.ttf
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf